diff -urN setroubleshoot-plugins-2.1.61.orig/po/ru.po setroubleshoot-plugins-2.1.61/po/ru.po
--- setroubleshoot-plugins-2.1.61.orig/po/ru.po	2010-12-13 20:15:43.985490757 +0300
+++ setroubleshoot-plugins-2.1.61/po/ru.po	2010-12-13 20:26:02.507005015 +0300
@@ -1313,7 +1313,7 @@
 msgstr ""
 "\n"
 "    SELinux запрещает $SOURCE_PATH доступ «$ACCESS» к устройству "
-"$TARGET_PATH. \n"
+"$TARGET_PATH.\n"
 "    "
 
 #: ../src/catchall_boolean.py:35
@@ -1330,10 +1330,10 @@
 msgstr ""
 "\n"
 "\n"
-"    SELinux отклонил запрос доступа от $SOURCE. Текущие настройки\n"
-"    логических переменных не разрешают доступ. Такой запрос не\n"
-"    ожидается от $SOURCE и может свидетельствовать о\n"
-"    попытке вторжения. Если же вы действительно хотите разрешить доступ,\n"
+"    SELinux отклонил запрос доступа от $SOURCE. Текущие настройки \n"
+"    логических переменных не разрешают доступ. Такой запрос не \n"
+"    ожидается от $SOURCE и может свидетельствовать о \n"
+"    попытке вторжения. Если же вы действительно хотите разрешить доступ, \n"
 "    потребуется изменить соответствующие логические переменные.\n"
 "    "
 
@@ -1394,15 +1394,6 @@
 "\n"
 "    "
 msgstr ""
-"\n"
-"\n"
-"    SELinux отклонил запрос доступа от $SOURCE. Такой запрос не\n"
-"    ожидается от $SOURCE и может свидетельствовать о\n"
-"    попытке вторжения. Но не исключено, что отдельные\n"
-"    версии или конфигурации приложения потребуют дополнительный\n"
-"    доступ.\n"
-"\n"
-"    "
 
 #: ../src/catchall.py:43
 msgid ""
